
version: "3"
services:
  server:
    container_name: server
    restart: always
    build: ./server
    ports:
      - "3002:3002"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    links:
      - mongo 

  chatserver:
    container_name: chatserver
    restart: always
    build: ./chatserver
    ports:
      - "4000:4000"
    volumes:
      - .:/home/node/app
      -  chatserver:/home/node/app/node_modules

 
  client:
    container_name: client
    restart: always
    build: ./client
    ports:
      - "80:3000"
    volumes:
       - .:/home/node/app
       -  client:/home/node/app/node_modules
    
  admin:
    container_name: admin
    restart: always
    build: ./admin
    ports:
      - "81:3001"
    volumes:
      - .:/home/node/app
      - admin:/home/node/app/node_modules
 
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
