
version: "3"
services:


 
  client:
    container_name: client
    restart: unless-stopped
    build: ./client
    ports:
      - "80:3000"
    volumes:
       - .:/home/node/app
   


  
 
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
