
version: "3"
services:
  server:
    container_name: server
    restart: unless-stopped
    build: ./server
    ports:
      - "3002:3002"
    volumes:
      - .:/home/node/app
     
    links:
      - mongo 

  chatserver:
    container_name: chatserver
    restart: unless-stopped
    build: ./chatserver
    ports:
      - "4000:4000"
    volumes:
      - .:/home/node/app
  

 
  client:
    container_name: client
    restart: unless-stopped
    build: ./client
  
    volumes:
       - ./client:/home/node/app/
       - ./client/node_modules:/home/node/app/node_modules
    command: ls -la
    ports:
      - "80:3000"
  

    
  admin:
    container_name: admin
    restart: unless-stopped
    build: ./admin
    ports:
      - "81:3001"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  
 
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
volumes:
    client: