
version: "3"
services:
  server:
    container_name: server
    restart: unless-stopped
    build: ./server
    ports:
      - "3002:3002"
    volumes:
      - ./server:/home/node/app
      - /home/node/app/node_modules
    links:
      - mongo 
    depends_on: 
      - mongo
  chatserver:
    container_name: chatserver
    restart: unless-stopped
    build: ./chatserver
    ports:
      - "4000:4000"
    volumes:
      - ./chatserver:/home/node/app
      - /home/node/app/node_modules
    links:
      - mongo 
    depends_on: 
      - mongo
 
  client:
    container_name: client
    restart: unless-stopped
    build: ./client
  
    volumes:
       - ./client:/home/node/app/
       - /home/node/app/node_modules
    ports:
      - "81:3001"
  

    
  admin:
    container_name: admin
    restart: unless-stopped
    build: ./admin
    ports:
      - "80:3000"
    volumes:
      - ./admin:/home/node/app/
      - /home/node/app/node_modules
    depends_on: 
      - mongo
 
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
